// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6KrrptYTua9fmKUrW6usQSDf3LafZFQQ',
    appId: '1:144710063111:web:1ce31bd2d522b1478cc6a2',
    messagingSenderId: '144710063111',
    projectId: 'the-payroll-system',
    authDomain: 'the-payroll-system.firebaseapp.com',
    storageBucket: 'the-payroll-system.appspot.com',
    measurementId: 'G-107RGN7R1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeaKte7Cdm4aM5p-n8XDL0YCOizO5Nwpo',
    appId: '1:144710063111:android:7e7f3726f2cf59e98cc6a2',
    messagingSenderId: '144710063111',
    projectId: 'the-payroll-system',
    storageBucket: 'the-payroll-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwrO8u-ZK7wJunTXx04XkonZ86Y6yzrQ',
    appId: '1:144710063111:ios:11e2ec0a242d48978cc6a2',
    messagingSenderId: '144710063111',
    projectId: 'the-payroll-system',
    storageBucket: 'the-payroll-system.appspot.com',
    iosBundleId: 'com.payroll.payrollApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMwrO8u-ZK7wJunTXx04XkonZ86Y6yzrQ',
    appId: '1:144710063111:ios:509f1fad674115378cc6a2',
    messagingSenderId: '144710063111',
    projectId: 'the-payroll-system',
    storageBucket: 'the-payroll-system.appspot.com',
    iosBundleId: 'com.payroll.payrollApp.RunnerTests',
  );
}
